name: stop_at_67
description: Stop at 67 - Precision timing game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  haptic_feedback: ^0.5.1+1
  flutter_tts: ^4.2.0
  google_mobile_ads: ^5.3.0
  purchases_flutter: ^8.0.0
  share_plus: ^10.1.0
  wakelock_plus: ^1.2.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
